# tcd (transcoder) configuration
# Transcoded must match the Transcoded value in urfd.ini

[Transcoder]
Transcoded    = D

DStarGainIn   =  16
DStarGainOut  = -16
DmrYsfGainIn  =  -3
DmrYsfGainOut =   0
