###### URFD CONFIGURATION ######
# Edit this file before starting the container.
# Do not use quotes, unless in a comment!

[Names]
Callsign = URF825

SysopEmail = example@example.com

# 2-letter country codes: https://www.iban.com/country-codes
Country = GB

Sponsor = G6PHF

DashboardUrl = http://xlx.g6phf.co.uk

# Bootstrap: address of any existing DHT node
Bootstrap = xrf757.openquad.net

[IP Addresses]
IPv4Binding = 0.0.0.0
# IPv6Binding = ::
IPv4External = 82.68.53.241
# IPv6External = f:e:d:c:b:a:9:0

[Modules]
Modules = ADMSZ
DescriptionA = NXDN Only (No transcode)
DescriptionD = Multimode Chat
DescriptionM = M17 Chat
DescriptionS = DStar Chat
DescriptionZ = Temp Meeting

#[Transcoder]
# Uncomment this entire section when tcd is enabled (set ENABLE_TCD=true in docker-compose.yml)
#Transcoded = A
#DStarGainIn   =  16
#DStarGainOut  = -16
#DmrYsfGainIn  =  -3
#DmrYsfGainOut =   0

[Brandmeister]
Enable = true
Port = 10002

[DPlus]
Port = 20001

[DCS]
Port = 30051

[DExtra]
Port = 30001

[M17]
Port = 17000

[MMDVM]
Port = 62030
DefaultId = 0

[NXDN]
Port = 41400
AutoLinkModule = A
ReflectorID = 825 

[P25]
Port = 41000
AutoLinkModule = D
ReflectorID = 825 

[URF]
Port = 10017

[YSF]
Port = 42000
AutoLinkModule = D
DefaultTxFreq = 446500000
DefaultRxFreq = 446500000
RegistrationID = 00825 
RegistrationName = UK XLX825
RegistrationDescription = URF Reflector

[DMR ID DB]
Mode = http
FilePath = /var/lib/urfd/dmrid.dat
URL = https://radioid.net/static/dmrid.dat
RefreshMin = 1440

[NXDN ID DB]
Mode = http
FilePath = /var/lib/urfd/nxdn.dat
URL = https://radioid.net/static/nxdn.csv
RefreshMin = 1440

[YSF TX/RX DB]
Mode = http
FilePath = /var/lib/urfd/ysfnode.dat
URL = http://xlxapi.rlx.lu/api/exportysfrepeaters.php
RefreshMin = 191

[Files]
PidPath       = /logs/urfd.pid
XmlPath       = /logs/urfd.xml
DHTSavePath   = /var/lib/urfd/urfd.dht.bin
WhitelistPath = /etc/urfd/urfd.whitelist
BlacklistPath = /etc/urfd/urfd.blacklist
InterlinkPath = /etc/urfd/urfd.interlink
